# Generated by Django 6.0.6 on 2026-06-26 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '__first__'),
        ('jobs', '__first__'),
        ('resumes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_score', models.IntegerField()),
                ('decision', models.CharField(max_length=20)),
                ('reasons', models.JSONField(default=list)),
                ('ai_summary', models.TextField()),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='applications.application')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.JSONField(default=list)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('resume_score', models.IntegerField(default=0)),
                ('summary', models.TextField()),
                ('analyzed_at', models.DateTimeField(auto_now=True)),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='resumes.resume')),
            ],
        ),
        migrations.CreateModel(
            name='JobMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('missing_skills', models.JSONField(default=list)),
                ('strengths', models.JSONField(default=list)),
                ('recommendations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('resume_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_matches', to='ai_engine.resumeanalysis')),
            ],
            options={
                'unique_together': {('resume_analysis', 'job')},
            },
        ),
    ]
